# Generated by Django 5.1.6 on 2025-02-14 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_groups_user_is_superuser_user_user_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('create_participant', 'Create participant'), ('update_participant', 'Update participant'), ('record_vitals', 'Create new participant vitals record'), ('update_vitals', 'Update participant vitals record'), ('view_vitals', 'View participant vitals'), ('create_adverse_event', 'Create adverse event report'), ('update_adverse_event', 'Update adverse event report'), ('view_adverse_event', 'View adverse event report'), ('create_blood_sample', 'Create blood sample collection report'), ('update_blood_sample', 'Update blood sample collection report'), ('view_blood_smaple', 'View blood sample collection report'), ('create_consent', 'Create informaed consent'), ('update_consent', 'Update informaed consent'), ('view_consent', 'View informed consent'), ('create_compliance', 'Create compliance report'), ('update_compliance', 'Update compliance report'), ('view_compliance', 'View complaince report(s)'), ('create_final_questionnaire', 'Create final questionnaire'), ('update_final_questionnaire', 'Update final questionnaire'), ('view_final_questionnaire', 'View final questionnaire'), ('create_exit_interview', 'Create exit interview record'), ('update_exit_interview', 'Update exit interview record'), ('view_exit_interview', 'View exit interview(s)'), ('view_logs', 'View logs of changes')]},
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('nurse', 'Nurse'), ('research_assistant', 'Research Assistant'), ('principle_investigator', 'Principle Investigator'), ('statistician', 'Statistician')], default='admin', max_length=50),
            preserve_default=False,
        ),
    ]
