# Generated by Django 2.2.1 on 2025-03-06 09:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mock_study_subjects', '0008_auto_20250306_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectscreening',
            name='report_datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 6, 9, 1, 28, 8632, tzinfo=utc), verbose_name='Report date and time.'),
        ),
    ]
