# Generated by Django 2.2.1 on 2025-03-06 09:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mock_study_subjects', '0013_auto_20250306_0909'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjectvisit',
            options={'verbose_name': 'Mock Study Subject Visit', 'verbose_name_plural': 'Mock Study Subject Visit'},
        ),
        migrations.AlterField(
            model_name='subjectscreening',
            name='report_datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 6, 9, 38, 34, 324386, tzinfo=utc), verbose_name='Report date and time.'),
        ),
    ]
