# Generated by Django 2.2.1 on 2025-03-06 10:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mock_study_subjects', '0015_auto_20250306_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectScreening',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screening_identifier', models.CharField(editable=False, max_length=36, unique=True, verbose_name='Eligibility Identifier')),
                ('report_datetime', models.DateTimeField(default=datetime.datetime(2025, 3, 6, 10, 11, 57, 179981, tzinfo=utc), verbose_name='Report date and time.')),
                ('has_hypertension', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], help_text="If 'No', then stop. Patient cannot be part of the study.", max_length=3, verbose_name='Have they been diagnosed with hypertension?')),
                ('eligible', models.BooleanField(default=False, editable=False)),
                ('age', models.IntegerField(help_text='If the patient is not between the ages of 30 and 65, then stop, they cannot be part of the study.')),
                ('is_pregnant', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], help_text="If 'Yes', then stop. The patient cannot be part of this study. ", max_length=3, verbose_name='Are they currently pregnant?')),
                ('is_breastfeeding', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], help_text="If 'Yes', then stop. The patient cannot be part of this study.", max_length=3, verbose_name='Is the patient currently breastfeeding?')),
                ('has_allergies_to_drug', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], help_text="If 'Yes', then stop. The patient cannot be part of this study.", max_length=3, verbose_name='Does the patient have any known allergies to XYZ Drug?')),
                ('has_history_of_severe_cardiovascular_events', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], help_text="If 'Yes', then stop. The patient cannot be part of this study.", max_length=3, verbose_name='Does the patient have a history of sever cardiovascular events within the last 6 (six) months?')),
                ('enrollment_site', models.CharField(choices=[('gaborone_private_hospital', 'Gaborone Private Hospital (GPH)'), ('nyangabgwe_referral_Hospital', 'Nyangabgwe Referral Hospital (NRH)'), ('princess_marina_hospital', 'Princess Marina Hospital (PMH)'), ('bokamoso_private_hospital', 'Bokamoso Private Hospital (BPH)')], help_text='Hospitals where subject is recruited.', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Mock Study Eligibility',
                'verbose_name_plural': 'Mock Study Eligibility',
            },
        ),
    ]
