# Generated by Django 2.2.1 on 2025-03-07 10:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mock_study_subjects', '0017_auto_20250307_0740'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjectconsent',
            options={'get_latest_by': 'consent_datetime', 'verbose_name': 'Mock Study Consent', 'verbose_name_plural': 'Mock Study Consent'},
        ),
        migrations.AlterField(
            model_name='subjectscreening',
            name='report_datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 7, 10, 27, 47, 640492, tzinfo=utc), verbose_name='Report date and time.'),
        ),
    ]
