# Generated by Django 2.2.1 on 2025-03-10 08:12

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('mock_study_subjects', '0018_auto_20250307_1027'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectLocator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_signed', models.DateField(default=django.utils.timezone.now, verbose_name='Date Locator Form signed ')),
                ('local_clinic', models.CharField(help_text='Please give clinic code.', max_length=75, verbose_name='When you stay in the village, what clinic/health post do you normally go to?')),
                ('home_village', models.CharField(max_length=75, verbose_name='Where is your home village?')),
                ('has_alt_contact', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=25, verbose_name='If we are unable to contact the person indicated above, is there another individual (including next of kin) with whom the study team can get in contact with?')),
                ('alt_contact_name', models.CharField(blank=True, help_text='include firstname and surname', max_length=35, null=True, verbose_name='Full Name of the responsible person')),
                ('alt_contact_rel', models.CharField(blank=True, max_length=35, null=True, verbose_name='Relationship to participant')),
                ('alt_contact_cell', models.CharField(blank=True, max_length=8, null=True, verbose_name='Cell number')),
                ('other_alt_contact_cell', models.CharField(blank=True, max_length=8, null=True, verbose_name='Cell number (alternate)')),
                ('alt_contact_tel', models.CharField(blank=True, max_length=8, null=True, verbose_name='Telephone number')),
                ('site', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subject_locator_site', to='sites.Site')),
            ],
            options={
                'verbose_name': 'Subject Locator',
                'verbose_name_plural': 'Subject Locator',
            },
        ),
        migrations.DeleteModel(
            name='EnrollmentManager',
        ),
        migrations.AlterField(
            model_name='subjectscreening',
            name='report_datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 10, 8, 12, 42, 390706, tzinfo=utc), verbose_name='Report date and time.'),
        ),
    ]
