# Generated by Django 2.2.1 on 2025-03-11 12:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mock_study_subjects', '0022_auto_20250311_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectBloodSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_identifier', models.CharField(max_length=20)),
                ('sample_identifier', models.CharField(max_length=20)),
                ('sample_type', models.CharField(max_length=10)),
                ('collection_date', models.DateField(default=datetime.datetime(2025, 3, 11, 12, 58, 48, 715173, tzinfo=utc))),
                ('collected_by', models.CharField(max_length=20)),
                ('collection_site', models.CharField(choices=[('gaborone_private_hospital', 'Gaborone Private Hospital (GPH)'), ('nyangabgwe_referral_Hospital', 'Nyangabgwe Referral Hospital (NRH)'), ('princess_marina_hospital', 'Princess Marina Hospital (PMH)'), ('bokamoso_private_hospital', 'Bokamoso Private Hospital (BPH)')], max_length=50)),
                ('volume', models.FloatField()),
                ('anticoagulant', models.CharField(max_length=50)),
                ('tube_type', models.CharField(max_length=50)),
                ('storage_location', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Subject Blood Sample',
                'verbose_name_plural': 'Subject Blood Samples',
            },
        ),
        migrations.AlterField(
            model_name='subjectscreening',
            name='report_datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 11, 12, 58, 48, 705178, tzinfo=utc), verbose_name='Report date and time.'),
        ),
    ]
