# Generated by Django 2.2.1 on 2025-03-11 14:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mock_study_subjects', '0024_auto_20250311_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiverPanelBloodTestResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_identifier', models.CharField(max_length=20)),
                ('test_date', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=10)),
                ('alt', models.FloatField(verbose_name='Alanine Aminotransferase (ALT)')),
                ('ast', models.FloatField(verbose_name='Aspartate Aminotransferase (AST)')),
                ('alp', models.FloatField(verbose_name='Alkaline Phosphatase (ALP)')),
                ('bilirubin_total', models.FloatField()),
                ('bilirubin_direct', models.FloatField()),
                ('bilirubin_indirect', models.FloatField()),
                ('albumin', models.FloatField()),
                ('total_protien', models.FloatField()),
            ],
            options={
                'verbose_name': 'Liver Pannel Blood Test Result',
                'verbose_name_plural': 'Liver Pannel Blood Test Result',
            },
        ),
        migrations.AlterField(
            model_name='subjectbloodsample',
            name='collection_date',
            field=models.DateField(default=datetime.datetime(2025, 3, 11, 14, 4, 37, 205990, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='subjectscreening',
            name='report_datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 11, 14, 4, 37, 196502, tzinfo=utc), verbose_name='Report date and time.'),
        ),
    ]
