# Generated by Django 2.2.1 on 2025-03-12 07:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mock_study_subjects', '0025_auto_20250311_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='CBCBloodTestResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_identifier', models.CharField(max_length=20)),
                ('sample_id', models.CharField(max_length=10)),
                ('red_blood_cell_count', models.FloatField()),
                ('hemoglobin', models.FloatField()),
                ('hematocrit', models.FloatField()),
                ('white_blood_cell_count', models.FloatField()),
                ('platelet_count', models.FloatField()),
            ],
            options={
                'verbose_name': 'CBC Blood Test Result',
                'verbose_name_plural': 'CBC Blood Test Results',
            },
        ),
        migrations.AlterField(
            model_name='subjectbloodsample',
            name='collection_date',
            field=models.DateField(default=datetime.datetime(2025, 3, 12, 7, 9, 57, 327560, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='subjectscreening',
            name='report_datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 12, 7, 9, 57, 315904, tzinfo=utc), verbose_name='Report date and time.'),
        ),
    ]
