# Generated by Django 2.2.1 on 2025-03-12 10:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mock_study_subjects', '0027_auto_20250312_0854'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdverseEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_identifier', models.CharField(max_length=10)),
                ('site', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('severity', models.CharField(max_length=20)),
                ('onset_date', models.DateField()),
                ('resolution_date', models.DateField()),
                ('action_taken', models.TextField()),
                ('outcome', models.TextField()),
                ('investigator_review', models.TextField()),
                ('investigator_comment', models.TextField()),
                ('study_intervention_relationship', models.CharField(max_length=50, verbose_name='How related was the clinical study to the adverse event?')),
            ],
            options={
                'verbose_name': 'Subject Adverse Event',
                'verbose_name_plural': 'Subject Adverse Events',
            },
        ),
        migrations.AlterField(
            model_name='subjectbloodsample',
            name='collection_date',
            field=models.DateField(default=datetime.datetime(2025, 3, 12, 10, 26, 19, 775493, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='subjectscreening',
            name='report_datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 12, 10, 26, 19, 763817, tzinfo=utc), verbose_name='Report date and time.'),
        ),
    ]
