# Generated by Django 2.2.1 on 2025-03-12 12:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mock_study_subjects', '0030_auto_20250312_1027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compliance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doses_taken', models.IntegerField()),
                ('prescribed_dosage', models.IntegerField()),
                ('subject_identifier', models.CharField(max_length=20)),
                ('subject_feedback', models.TextField()),
                ('investigator_comments', models.TextField()),
            ],
            options={
                'verbose_name': 'Compliance Form',
                'verbose_name_plural': 'Compliance Forms',
            },
        ),
        migrations.AlterField(
            model_name='subjectbloodsample',
            name='collection_date',
            field=models.DateField(default=datetime.datetime(2025, 3, 12, 12, 39, 59, 741452, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='subjectscreening',
            name='report_datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 12, 12, 39, 59, 728872, tzinfo=utc), verbose_name='Report date and time.'),
        ),
    ]
