# Generated by Django 2.2.1 on 2025-03-13 09:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mock_study_subjects', '0035_auto_20250313_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adverseevent',
            name='onset_date',
            field=models.DateField(default=datetime.datetime(2025, 3, 13, 9, 55, 52, 36531, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='adverseevent',
            name='site',
            field=models.CharField(choices=[('gaborone_private_hospital', 'Gaborone Private Hospital (GPH)'), ('nyangabgwe_referral_hospital', 'Nyangabgwe Referral Hospital (NRH)'), ('princess_marina_hospital', 'Princess Marina Hospital (PMH)'), ('bokamoso_private_hospital', 'Bokamoso Private Hospital (BPH)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='site',
            field=models.CharField(choices=[('gaborone_private_hospital', 'Gaborone Private Hospital (GPH)'), ('nyangabgwe_referral_hospital', 'Nyangabgwe Referral Hospital (NRH)'), ('princess_marina_hospital', 'Princess Marina Hospital (PMH)'), ('bokamoso_private_hospital', 'Bokamoso Private Hospital (BPH)')], max_length=30),
        ),
        migrations.AlterField(
            model_name='cbcbloodtestresult',
            name='date_tested',
            field=models.DateField(default=datetime.datetime(2025, 3, 13, 9, 55, 52, 35834, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='subjectbloodsample',
            name='collection_date',
            field=models.DateField(default=datetime.datetime(2025, 3, 13, 9, 55, 52, 34425, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='subjectbloodsample',
            name='collection_site',
            field=models.CharField(choices=[('gaborone_private_hospital', 'Gaborone Private Hospital (GPH)'), ('nyangabgwe_referral_hospital', 'Nyangabgwe Referral Hospital (NRH)'), ('princess_marina_hospital', 'Princess Marina Hospital (PMH)'), ('bokamoso_private_hospital', 'Bokamoso Private Hospital (BPH)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='subjectscreening',
            name='enrollment_site',
            field=models.CharField(choices=[('gaborone_private_hospital', 'Gaborone Private Hospital (GPH)'), ('nyangabgwe_referral_hospital', 'Nyangabgwe Referral Hospital (NRH)'), ('princess_marina_hospital', 'Princess Marina Hospital (PMH)'), ('bokamoso_private_hospital', 'Bokamoso Private Hospital (BPH)')], help_text='Hospitals where subject is recruited.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subjectscreening',
            name='report_datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 13, 9, 55, 52, 24098, tzinfo=utc), verbose_name='Report date and time.'),
        ),
        migrations.AlterField(
            model_name='subjectvitals',
            name='collection_site',
            field=models.CharField(choices=[('gaborone_private_hospital', 'Gaborone Private Hospital (GPH)'), ('nyangabgwe_referral_hospital', 'Nyangabgwe Referral Hospital (NRH)'), ('princess_marina_hospital', 'Princess Marina Hospital (PMH)'), ('bokamoso_private_hospital', 'Bokamoso Private Hospital (BPH)')], max_length=50),
        ),
    ]
