# Generated by Django 2.2.1 on 2025-04-25 03:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mock_study_prn', '0002_auto_20250424_0922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compliancereport',
            name='has_side_effects',
        ),
        migrations.RemoveField(
            model_name='compliancereport',
            name='missed_days',
        ),
        migrations.RemoveField(
            model_name='compliancereport',
            name='side_effects',
        ),
        migrations.RemoveField(
            model_name='historicalcompliancereport',
            name='has_side_effects',
        ),
        migrations.RemoveField(
            model_name='historicalcompliancereport',
            name='missed_days',
        ),
        migrations.RemoveField(
            model_name='historicalcompliancereport',
            name='side_effects',
        ),
        migrations.AddField(
            model_name='compliancereport',
            name='missed_dosses_reason',
            field=models.TextField(blank=True, null=True, verbose_name='If you have not taken the prescribed dossage please explain why?'),
        ),
        migrations.AddField(
            model_name='compliancereport',
            name='missed_visits',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compliancereport',
            name='report_datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 25, 3, 26, 55, 724685, tzinfo=utc), verbose_name='Amount of visits missed'),
        ),
        migrations.AddField(
            model_name='historicalcompliancereport',
            name='missed_dosses_reason',
            field=models.TextField(blank=True, null=True, verbose_name='If you have not taken the prescribed dossage please explain why?'),
        ),
        migrations.AddField(
            model_name='historicalcompliancereport',
            name='missed_visits',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalcompliancereport',
            name='report_datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 25, 3, 26, 55, 724685, tzinfo=utc), verbose_name='Amount of visits missed'),
        ),
        migrations.AlterField(
            model_name='adverseevent',
            name='onset_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='finalquestionnaire',
            name='study_purpose_grievance',
            field=models.TextField(blank=True, null=True, verbose_name='Please leave a comment on why you believe the purpose of the study was not clearly explained to you.'),
        ),
        migrations.AlterField(
            model_name='historicalfinalquestionnaire',
            name='study_purpose_grievance',
            field=models.TextField(blank=True, null=True, verbose_name='Please leave a comment on why you believe the purpose of the study was not clearly explained to you.'),
        ),
    ]
