# Generated by Django 2.2.1 on 2025-04-25 06:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mock_study_prn', '0003_auto_20250425_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliancereport',
            name='report_datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 25, 6, 51, 10, 436039, tzinfo=utc), verbose_name='Amount of visits missed'),
        ),
        migrations.AlterField(
            model_name='historicalcompliancereport',
            name='report_datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 25, 6, 51, 10, 436039, tzinfo=utc), verbose_name='Amount of visits missed'),
        ),
    ]
