# Generated by Django 2.2.1 on 2025-02-24 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaticipantVitals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_identifier', models.CharField(max_length=50)),
                ('height', models.FloatField()),
                ('blood_pressure', models.CharField(max_length=50)),
                ('weight', models.FloatField()),
                ('baseline', models.BooleanField(default=True)),
            ],
        ),
    ]
