# Generated by Django 2.2.1 on 2025-02-24 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PaticipantVitals',
            new_name='ParticipantVital',
        ),
    ]
