# Generated by Django 2.2.1 on 2025-02-24 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20250224_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdverseEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_identifier', models.CharField(max_length=50)),
                ('severity', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], max_length=10)),
                ('onset_date', models.DateField()),
                ('resolution_date', models.DateField()),
                ('action_taken', models.CharField(max_length=500)),
                ('outcome', models.CharField(max_length=500)),
                ('investigator_review', models.CharField(max_length=500)),
            ],
        ),
    ]
