# Generated by Django 2.2.1 on 2025-02-24 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_adverseevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_identifier', models.CharField(max_length=50)),
                ('sample_id', models.CharField(max_length=20)),
                ('collection_date', models.DateTimeField()),
                ('requested_test', models.CharField(max_length=256)),
                ('phlebotomist_signature', models.CharField(max_length=256)),
            ],
        ),
    ]
