# Generated by Django 2.2.1 on 2025-02-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_bloodsample'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_identifier', models.CharField(max_length=50)),
                ('dose_taken', models.CharField(max_length=100)),
                ('dose_prescribed', models.CharField(max_length=100)),
                ('participant_feedback', models.CharField(max_length=500)),
                ('investigator_comment', models.CharField(max_length=500)),
            ],
        ),
    ]
