# Generated by Django 2.2.1 on 2025-02-24 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_complianceform'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExitInterview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_identifier', models.CharField(max_length=50)),
                ('summary_of_parricipant_experience', models.CharField(max_length=500)),
                ('investigator_observations', models.CharField(max_length=500)),
                ('final_comments_and_recommendations', models.CharField(max_length=500)),
            ],
        ),
    ]
