# Generated by Django 2.2.1 on 2025-02-24 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_exitinterview'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalQuestionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_identifier', models.CharField(max_length=50)),
                ('participant_experience', models.CharField(max_length=500)),
                ('perceived_benefits', models.CharField(max_length=500)),
                ('perceived_challenges', models.CharField(max_length=500)),
                ('willingness_to_participate_in_future_studies', models.CharField(choices=[('unwilling', 'Unwilling'), ('moderatly_willing', 'Moderate Willing'), ('very_willing', 'Very Willing')], max_length=20)),
            ],
        ),
    ]
