# Generated by Django 2.2.1 on 2025-02-24 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_finalquestionnaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalquestionnaire',
            name='willingness_to_participate_in_future_studies',
            field=models.CharField(choices=[('unwilling', 'Unwilling'), ('moderatly', 'Moderate'), ('very', 'Very')], max_length=20),
        ),
    ]
