# Generated by Django 5.1.4 on 2025-02-25 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20250224_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adverseevent',
            name='action_taken',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='adverseevent',
            name='investigator_review',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='adverseevent',
            name='outcome',
            field=models.TextField(max_length=500),
        ),
    ]
