# Generated by Django 5.1.4 on 2025-02-25 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_adverseevent_action_taken_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complianceform',
            name='investigator_comment',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='complianceform',
            name='participant_feedback',
            field=models.TextField(),
        ),
    ]
