# Generated by Django 5.1.4 on 2025-02-25 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_complianceform_investigator_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exitinterview',
            name='summary_of_parricipant_experience',
        ),
        migrations.AlterField(
            model_name='exitinterview',
            name='final_comments_and_recommendations',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='exitinterview',
            name='investigator_observations',
            field=models.TextField(),
        ),
    ]
