# Generated by Django 2.2.1 on 2025-02-25 12:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_exitinterview_summary_of_parricipant_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodsample',
            name='collection_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 25, 12, 50, 6, 179486, tzinfo=utc)),
        ),
    ]
