# Generated by Django 2.2.1 on 2025-02-25 13:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_auto_20250225_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodsample',
            name='collection_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 25, 13, 51, 12, 190182, tzinfo=utc)),
        ),
    ]
