# Generated by Django 2.2.1 on 2025-02-26 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_auto_20250225_1340 2'),
        ('base', '0015_auto_20250225_1351 2'),
        ('base', '0015_auto_20250225_1351'),
        ('base', '0013_auto_20250225_1250 2'),
    ]

    operations = [
    ]
