# Generated by Django 2.2.1 on 2025-02-26 10:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_merge_20250226_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodsample',
            name='collection_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 26, 10, 16, 56, 86565, tzinfo=utc)),
        ),
    ]
