# Generated by Django 2.2.1 on 2025-02-26 12:53

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_auto_20250226_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='prescribed_by',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='base.Doctors'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bloodsample',
            name='collection_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 26, 12, 53, 38, 785597, tzinfo=utc)),
        ),
    ]
