# Generated by Django 2.2.1 on 2025-02-26 12:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_auto_20250226_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodsample',
            name='collection_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 26, 12, 58, 1, 165474, tzinfo=utc)),
        ),
    ]
