# Generated by Django 2.2.1 on 2025-02-26 12:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_auto_20250226_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='allergy',
            name='reaction',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bloodsample',
            name='collection_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 26, 12, 58, 15, 358066, tzinfo=utc)),
        ),
    ]
