# Generated by Django 2.2.1 on 2025-02-26 13:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_auto_20250226_1258'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Doctors',
            new_name='Doctor',
        ),
        migrations.AlterField(
            model_name='bloodsample',
            name='collection_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 26, 13, 5, 21, 801555, tzinfo=utc)),
        ),
    ]
