# Generated by Django 2.2.1 on 2025-03-05 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mock_study_subjects', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EnrollementManager',
            new_name='EnrollmentManager',
        ),
    ]
