# Generated by Django 2.2.1 on 2025-04-04 07:36

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mock_study_subjects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adverseevent',
            name='onset_date',
            field=models.DateField(default=datetime.datetime(2025, 4, 4, 7, 36, 17, 15327, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cbcbloodtestresult',
            name='date_tested',
            field=models.DateField(default=datetime.datetime(2025, 4, 4, 7, 36, 17, 14176, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='historicalsubjectscreening',
            name='report_datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 4, 7, 36, 16, 809818, tzinfo=utc), verbose_name='Report date and time.'),
        ),
        migrations.AlterField(
            model_name='subjectbloodsample',
            name='collection_date',
            field=models.DateField(default=datetime.datetime(2025, 4, 4, 7, 36, 17, 12101, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='subjectscreening',
            name='report_datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 4, 7, 36, 16, 809818, tzinfo=utc), verbose_name='Report date and time.'),
        ),
        migrations.AlterField(
            model_name='subjectvitals',
            name='diastolic_blood_pressure',
            field=models.IntegerField(default=0, help_text='mmHg', validators=[django.core.validators.MaxValueValidator(250), django.core.validators.MinValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='subjectvitals',
            name='heart_rate',
            field=models.IntegerField(default=0, help_text='bpm', validators=[django.core.validators.MaxValueValidator(200), django.core.validators.MinValueValidator(30)]),
        ),
        migrations.AlterField(
            model_name='subjectvitals',
            name='height',
            field=models.DecimalField(decimal_places=1, default=0, help_text='cm', max_digits=4, validators=[django.core.validators.MaxValueValidator(300), django.core.validators.MinValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='subjectvitals',
            name='systolic_blood_pressure',
            field=models.IntegerField(default=0, help_text='mmHg', validators=[django.core.validators.MaxValueValidator(250), django.core.validators.MinValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='subjectvitals',
            name='weight',
            field=models.DecimalField(decimal_places=1, default=0, help_text='kg', max_digits=4, validators=[django.core.validators.MaxValueValidator(500), django.core.validators.MinValueValidator(30)]),
        ),
    ]
