# Generated by Django 2.2.1 on 2025-03-17 06:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mock_study_subjects', '0002_auto_20250317_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adverseevent',
            name='onset_date',
            field=models.DateField(default=datetime.datetime(2025, 3, 17, 6, 47, 3, 959945, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cbcbloodtestresult',
            name='date_tested',
            field=models.DateField(default=datetime.datetime(2025, 3, 17, 6, 47, 3, 958870, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='historicalsubjectconsent',
            name='subject_identifier',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Subject Identifier'),
        ),
        migrations.AlterField(
            model_name='historicalsubjectscreening',
            name='report_datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 17, 6, 47, 3, 559918, tzinfo=utc), verbose_name='Report date and time.'),
        ),
        migrations.AlterField(
            model_name='subjectbloodsample',
            name='collection_date',
            field=models.DateField(default=datetime.datetime(2025, 3, 17, 6, 47, 3, 956834, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='subjectconsent',
            name='subject_identifier',
            field=models.CharField(max_length=50, unique=True, verbose_name='Subject Identifier'),
        ),
        migrations.AlterField(
            model_name='subjectscreening',
            name='report_datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 17, 6, 47, 3, 559918, tzinfo=utc), verbose_name='Report date and time.'),
        ),
    ]
