# Generated by Django 2.2.1 on 2025-03-06 07:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mock_study_subjects', '0003_subjectscreening'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectscreening',
            name='report_datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 6, 7, 30, 9, 556107, tzinfo=utc), verbose_name='Report date and time.'),
        ),
    ]
