# Generated by Django 2.2.1 on 2025-03-18 06:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mock_study_subjects', '0004_auto_20250317_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsubjectlocator',
            name='home_village',
        ),
        migrations.RemoveField(
            model_name='historicalsubjectlocator',
            name='local_clinic',
        ),
        migrations.RemoveField(
            model_name='subjectlocator',
            name='home_village',
        ),
        migrations.RemoveField(
            model_name='subjectlocator',
            name='local_clinic',
        ),
        migrations.AlterField(
            model_name='adverseevent',
            name='onset_date',
            field=models.DateField(default=datetime.datetime(2025, 3, 18, 6, 22, 21, 516127, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cbcbloodtestresult',
            name='date_tested',
            field=models.DateField(default=datetime.datetime(2025, 3, 18, 6, 22, 21, 514884, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='historicalsubjectscreening',
            name='report_datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 18, 6, 22, 20, 557101, tzinfo=utc), verbose_name='Report date and time.'),
        ),
        migrations.AlterField(
            model_name='subjectbloodsample',
            name='collection_date',
            field=models.DateField(default=datetime.datetime(2025, 3, 18, 6, 22, 21, 512592, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='subjectscreening',
            name='report_datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 18, 6, 22, 20, 557101, tzinfo=utc), verbose_name='Report date and time.'),
        ),
    ]
