# Generated by Django 2.2.1 on 2025-03-18 09:20

import _socket
import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django_revision.revision_field
import edc_base.model_fields.hostname_modification_field
import edc_base.model_fields.userfield
import edc_base.model_fields.uuid_auto_field
import edc_base.model_validators.date
import edc_base.utils
import edc_protocol.validators


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('mock_study_subjects', '0005_auto_20250318_0622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectvitals',
            name='anatomical_location_of_measurement',
        ),
        migrations.RemoveField(
            model_name='subjectvitals',
            name='collection_site',
        ),
        migrations.RemoveField(
            model_name='subjectvitals',
            name='is_baseline',
        ),
        migrations.RemoveField(
            model_name='subjectvitals',
            name='measurement_date',
        ),
        migrations.RemoveField(
            model_name='subjectvitals',
            name='subject_identifier',
        ),
        migrations.RemoveField(
            model_name='subjectvitals',
            name='were_vitals_collected',
        ),
        migrations.AddField(
            model_name='subjectvitals',
            name='consent_model',
            field=models.CharField(editable=False, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subjectvitals',
            name='consent_version',
            field=models.CharField(editable=False, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='subjectvitals',
            name='created',
            field=models.DateTimeField(blank=True, default=edc_base.utils.get_utcnow),
        ),
        migrations.AddField(
            model_name='subjectvitals',
            name='device_created',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='subjectvitals',
            name='device_modified',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='subjectvitals',
            name='heart_rate',
            field=models.IntegerField(default=60, help_text='bpm'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjectvitals',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AddField(
            model_name='subjectvitals',
            name='hostname_modified',
            field=edc_base.model_fields.hostname_modification_field.HostnameModificationField(blank=True, help_text='System field. (modified on every save)', max_length=50),
        ),
        migrations.AddField(
            model_name='subjectvitals',
            name='modified',
            field=models.DateTimeField(blank=True, default=edc_base.utils.get_utcnow),
        ),
        migrations.AddField(
            model_name='subjectvitals',
            name='report_datetime',
            field=models.DateTimeField(default=edc_base.utils.get_utcnow, help_text="If reporting today, use today's date/time, otherwise use the date/time this information was reported.", validators=[edc_protocol.validators.datetime_not_before_study_start, edc_base.model_validators.date.datetime_not_future], verbose_name='Report Date'),
        ),
        migrations.AddField(
            model_name='subjectvitals',
            name='revision',
            field=django_revision.revision_field.RevisionField(blank=True, editable=False, help_text='System field. Git repository tag:branch:commit.', max_length=75, null=True, verbose_name='Revision'),
        ),
        migrations.AddField(
            model_name='subjectvitals',
            name='site',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='sites.Site'),
        ),
        migrations.AddField(
            model_name='subjectvitals',
            name='subject_visit',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.PROTECT, to='mock_study_subjects.SubjectVisit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjectvitals',
            name='user_created',
            field=edc_base.model_fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user created'),
        ),
        migrations.AddField(
            model_name='subjectvitals',
            name='user_modified',
            field=edc_base.model_fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user modified'),
        ),
        migrations.AlterField(
            model_name='adverseevent',
            name='onset_date',
            field=models.DateField(default=datetime.datetime(2025, 3, 18, 9, 20, 13, 728230, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cbcbloodtestresult',
            name='date_tested',
            field=models.DateField(default=datetime.datetime(2025, 3, 18, 9, 20, 13, 727027, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='historicalsubjectscreening',
            name='report_datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 18, 9, 20, 13, 476427, tzinfo=utc), verbose_name='Report date and time.'),
        ),
        migrations.AlterField(
            model_name='historicalsubjectvisit',
            name='info_source',
            field=models.CharField(choices=[('Clinic visit w/ subject', 'Clinic visit with participant'), ('Other contact w/ subject', 'Other contact with participant (i.e telephone call)'), ('Contact w/ family/design', 'Contact with family or designated person who can provide information'), ('OTHER', 'Other,specify')], max_length=40, verbose_name='What is the main source of this information?'),
        ),
        migrations.AlterField(
            model_name='historicalsubjectvisit',
            name='reason',
            field=models.CharField(choices=[('Weekly visit/contact', 'Weekly visit/contact'), ('Unscheduled visit/contact', 'Unscheduled visit/contact'), ('Missed missed visit', 'Missed weekly visit'), ('Lost to follow-up', 'Lost to follow-up (use only when taking subject off study)'), ('Death', 'Death'), ('off study', 'Off study'), ('deferred', 'Deferred')], max_length=25, verbose_name='What is the reason for this visit report?'),
        ),
        migrations.AlterField(
            model_name='historicalsubjectvisit',
            name='reason_unscheduled',
            field=models.CharField(choices=[('Patient called', 'Patient called to come for visit'), ('N/A', 'Not Applicable'), ('OTHER', 'Other, specify:')], default='N/A', max_length=50, verbose_name="If 'Unscheduled' above, provide reason for the unscheduled visit"),
        ),
        migrations.AlterField(
            model_name='subjectbloodsample',
            name='collection_date',
            field=models.DateField(default=datetime.datetime(2025, 3, 18, 9, 20, 13, 724241, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='subjectscreening',
            name='report_datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 18, 9, 20, 13, 476427, tzinfo=utc), verbose_name='Report date and time.'),
        ),
        migrations.AlterField(
            model_name='subjectvisit',
            name='info_source',
            field=models.CharField(choices=[('Clinic visit w/ subject', 'Clinic visit with participant'), ('Other contact w/ subject', 'Other contact with participant (i.e telephone call)'), ('Contact w/ family/design', 'Contact with family or designated person who can provide information'), ('OTHER', 'Other,specify')], max_length=40, verbose_name='What is the main source of this information?'),
        ),
        migrations.AlterField(
            model_name='subjectvisit',
            name='reason',
            field=models.CharField(choices=[('Weekly visit/contact', 'Weekly visit/contact'), ('Unscheduled visit/contact', 'Unscheduled visit/contact'), ('Missed missed visit', 'Missed weekly visit'), ('Lost to follow-up', 'Lost to follow-up (use only when taking subject off study)'), ('Death', 'Death'), ('off study', 'Off study'), ('deferred', 'Deferred')], max_length=25, verbose_name='What is the reason for this visit report?'),
        ),
        migrations.AlterField(
            model_name='subjectvisit',
            name='reason_unscheduled',
            field=models.CharField(choices=[('Patient called', 'Patient called to come for visit'), ('N/A', 'Not Applicable'), ('OTHER', 'Other, specify:')], default='N/A', max_length=50, verbose_name="If 'Unscheduled' above, provide reason for the unscheduled visit"),
        ),
        migrations.AlterField(
            model_name='subjectvitals',
            name='diastolic_blood_pressure',
            field=models.IntegerField(help_text='mmHg'),
        ),
        migrations.AlterField(
            model_name='subjectvitals',
            name='height',
            field=models.DecimalField(decimal_places=1, help_text='cm', max_digits=4),
        ),
        migrations.AlterField(
            model_name='subjectvitals',
            name='id',
            field=edc_base.model_fields.uuid_auto_field.UUIDAutoField(blank=True, editable=False, help_text='System auto field. UUID primary key.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subjectvitals',
            name='systolic_blood_pressure',
            field=models.IntegerField(help_text='mmHg'),
        ),
        migrations.AlterField(
            model_name='subjectvitals',
            name='weight',
            field=models.DecimalField(decimal_places=1, help_text='kg', max_digits=4),
        ),
    ]
