# Generated by Django 2.2.1 on 2025-03-21 05:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mock_study_subjects', '0009_auto_20250321_0351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsubjectscreening',
            name='subject_identifier',
        ),
        migrations.RemoveField(
            model_name='subjectscreening',
            name='subject_identifier',
        ),
        migrations.AlterField(
            model_name='adverseevent',
            name='onset_date',
            field=models.DateField(default=datetime.datetime(2025, 3, 21, 5, 13, 53, 62829, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cbcbloodtestresult',
            name='date_tested',
            field=models.DateField(default=datetime.datetime(2025, 3, 21, 5, 13, 53, 61643, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='historicalsubjectscreening',
            name='has_allergies_to_drug',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], help_text="If 'Yes', then stop. The patient cannot be part of this study.", max_length=3, verbose_name='Does the patient have any known allergies to XYZ Drug?'),
        ),
        migrations.AlterField(
            model_name='historicalsubjectscreening',
            name='has_history_of_severe_cardiovascular_events',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], help_text="If 'Yes', then stop. The patient cannot be part of this study.", max_length=3, verbose_name='Does the patient have a history of sever cardiovascular events within the last 6 (six) months?'),
        ),
        migrations.AlterField(
            model_name='historicalsubjectscreening',
            name='has_hypertension',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], help_text="If 'No', then stop. Patient cannot be part of the study.", max_length=3, verbose_name='Have they been diagnosed with hypertension?'),
        ),
        migrations.AlterField(
            model_name='historicalsubjectscreening',
            name='is_breastfeeding',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], help_text="If 'Yes', then stop. The patient cannot be part of this study.", max_length=3, verbose_name='Is the patient currently breastfeeding?'),
        ),
        migrations.AlterField(
            model_name='historicalsubjectscreening',
            name='is_pregnant',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], help_text="If 'Yes', then stop. The patient cannot be part of this study. ", max_length=3, verbose_name='Are they currently pregnant?'),
        ),
        migrations.AlterField(
            model_name='historicalsubjectscreening',
            name='report_datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 21, 5, 13, 52, 811665, tzinfo=utc), verbose_name='Report date and time.'),
        ),
        migrations.AlterField(
            model_name='subjectbloodsample',
            name='collection_date',
            field=models.DateField(default=datetime.datetime(2025, 3, 21, 5, 13, 53, 59321, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='subjectscreening',
            name='has_allergies_to_drug',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], help_text="If 'Yes', then stop. The patient cannot be part of this study.", max_length=3, verbose_name='Does the patient have any known allergies to XYZ Drug?'),
        ),
        migrations.AlterField(
            model_name='subjectscreening',
            name='has_history_of_severe_cardiovascular_events',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], help_text="If 'Yes', then stop. The patient cannot be part of this study.", max_length=3, verbose_name='Does the patient have a history of sever cardiovascular events within the last 6 (six) months?'),
        ),
        migrations.AlterField(
            model_name='subjectscreening',
            name='has_hypertension',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], help_text="If 'No', then stop. Patient cannot be part of the study.", max_length=3, verbose_name='Have they been diagnosed with hypertension?'),
        ),
        migrations.AlterField(
            model_name='subjectscreening',
            name='is_breastfeeding',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], help_text="If 'Yes', then stop. The patient cannot be part of this study.", max_length=3, verbose_name='Is the patient currently breastfeeding?'),
        ),
        migrations.AlterField(
            model_name='subjectscreening',
            name='is_pregnant',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], help_text="If 'Yes', then stop. The patient cannot be part of this study. ", max_length=3, verbose_name='Are they currently pregnant?'),
        ),
        migrations.AlterField(
            model_name='subjectscreening',
            name='report_datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 21, 5, 13, 52, 811665, tzinfo=utc), verbose_name='Report date and time.'),
        ),
    ]
