# Generated by Django 2.2.1 on 2025-04-14 07:53

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mock_study_subjects', '0009_auto_20250414_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adverseevent',
            name='onset_date',
            field=models.DateField(default=datetime.datetime(2025, 4, 14, 7, 53, 15, 124958, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cbcbloodtestresult',
            name='date_tested',
            field=models.DateField(default=datetime.datetime(2025, 4, 14, 7, 53, 15, 124184, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='historicalsubjectconsent',
            name='screening_identifier',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='mock_study_subjects.SubjectScreening'),
        ),
        migrations.AlterField(
            model_name='historicalsubjectscreening',
            name='report_datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 14, 7, 53, 14, 920378, tzinfo=utc), verbose_name='Report date and time.'),
        ),
        migrations.AlterField(
            model_name='subjectbloodsample',
            name='collection_date',
            field=models.DateField(default=datetime.datetime(2025, 4, 14, 7, 53, 15, 122709, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='subjectconsent',
            name='screening_identifier',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='mock_study_subjects.SubjectScreening'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subjectscreening',
            name='report_datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 14, 7, 53, 14, 920378, tzinfo=utc), verbose_name='Report date and time.'),
        ),
    ]
