# Generated by Django 2.2.1 on 2025-04-14 08:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mock_study_subjects', '0010_auto_20250414_0753'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjectconsent',
            options={'get_latest_by': 'consent_datetime', 'ordering': ('created',), 'verbose_name': 'Mock Study Consent', 'verbose_name_plural': 'Mock Study Consent'},
        ),
        migrations.AlterField(
            model_name='adverseevent',
            name='onset_date',
            field=models.DateField(default=datetime.datetime(2025, 4, 14, 8, 51, 24, 359081, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cbcbloodtestresult',
            name='date_tested',
            field=models.DateField(default=datetime.datetime(2025, 4, 14, 8, 51, 24, 358060, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='historicalsubjectscreening',
            name='report_datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 14, 8, 51, 24, 133912, tzinfo=utc), verbose_name='Report date and time.'),
        ),
        migrations.AlterField(
            model_name='subjectbloodsample',
            name='collection_date',
            field=models.DateField(default=datetime.datetime(2025, 4, 14, 8, 51, 24, 355570, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='subjectscreening',
            name='report_datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 14, 8, 51, 24, 133912, tzinfo=utc), verbose_name='Report date and time.'),
        ),
        migrations.AlterUniqueTogether(
            name='subjectconsent',
            unique_together={('subject_identifier', 'version'), ('first_name', 'dob', 'initials', 'version')},
        ),
    ]
