# Generated by Django 2.2.1 on 2025-03-21 08:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import edc_base.model_fields.custom_fields


class Migration(migrations.Migration):

    dependencies = [
        ('mock_study_subjects', '0011_auto_20250321_0756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsubjectconsent',
            name='citizen',
        ),
        migrations.RemoveField(
            model_name='historicalsubjectconsent',
            name='legal_marriage',
        ),
        migrations.RemoveField(
            model_name='historicalsubjectconsent',
            name='marriage_certificate',
        ),
        migrations.RemoveField(
            model_name='historicalsubjectconsent',
            name='marriage_certificate_no',
        ),
        migrations.RemoveField(
            model_name='subjectconsent',
            name='citizen',
        ),
        migrations.RemoveField(
            model_name='subjectconsent',
            name='legal_marriage',
        ),
        migrations.RemoveField(
            model_name='subjectconsent',
            name='marriage_certificate',
        ),
        migrations.RemoveField(
            model_name='subjectconsent',
            name='marriage_certificate_no',
        ),
        migrations.AddField(
            model_name='historicalsubjectconsent',
            name='other_idenity_type',
            field=edc_base.model_fields.custom_fields.OtherCharField(blank=True, max_length=35, null=True, verbose_name='If Other, specify ...'),
        ),
        migrations.AddField(
            model_name='subjectconsent',
            name='other_idenity_type',
            field=edc_base.model_fields.custom_fields.OtherCharField(blank=True, max_length=35, null=True, verbose_name='If Other, specify ...'),
        ),
        migrations.AlterField(
            model_name='adverseevent',
            name='onset_date',
            field=models.DateField(default=datetime.datetime(2025, 3, 21, 8, 27, 8, 174079, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cbcbloodtestresult',
            name='date_tested',
            field=models.DateField(default=datetime.datetime(2025, 3, 21, 8, 27, 8, 172830, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='historicalsubjectconsent',
            name='identity_type',
            field=models.CharField(choices=[('country_id', 'Country ID number'), ('drivers_licence', "Driver's license"), ('passport', 'Passport'), ('country_id_rcpt', 'Country ID receipt'), ('OTHER', 'Other')], max_length=25, verbose_name='What type of identity number is this?'),
        ),
        migrations.AlterField(
            model_name='historicalsubjectscreening',
            name='report_datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 21, 8, 27, 7, 922501, tzinfo=utc), verbose_name='Report date and time.'),
        ),
        migrations.AlterField(
            model_name='subjectbloodsample',
            name='collection_date',
            field=models.DateField(default=datetime.datetime(2025, 3, 21, 8, 27, 8, 170610, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='subjectconsent',
            name='identity_type',
            field=models.CharField(choices=[('country_id', 'Country ID number'), ('drivers_licence', "Driver's license"), ('passport', 'Passport'), ('country_id_rcpt', 'Country ID receipt'), ('OTHER', 'Other')], max_length=25, verbose_name='What type of identity number is this?'),
        ),
        migrations.AlterField(
            model_name='subjectscreening',
            name='report_datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 21, 8, 27, 7, 922501, tzinfo=utc), verbose_name='Report date and time.'),
        ),
    ]
