# Generated by Django 2.2.1 on 2025-03-21 09:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mock_study_subjects', '0012_auto_20250321_0827'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='subjectlocator',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='historicalsubjectlocator',
            name='alt_contact_cell',
        ),
        migrations.RemoveField(
            model_name='historicalsubjectlocator',
            name='alt_contact_name',
        ),
        migrations.RemoveField(
            model_name='historicalsubjectlocator',
            name='alt_contact_rel',
        ),
        migrations.RemoveField(
            model_name='historicalsubjectlocator',
            name='alt_contact_tel',
        ),
        migrations.RemoveField(
            model_name='historicalsubjectlocator',
            name='has_alt_contact',
        ),
        migrations.RemoveField(
            model_name='historicalsubjectlocator',
            name='other_alt_contact_cell',
        ),
        migrations.RemoveField(
            model_name='historicalsubjectlocator',
            name='site',
        ),
        migrations.RemoveField(
            model_name='subjectlocator',
            name='alt_contact_cell',
        ),
        migrations.RemoveField(
            model_name='subjectlocator',
            name='alt_contact_name',
        ),
        migrations.RemoveField(
            model_name='subjectlocator',
            name='alt_contact_rel',
        ),
        migrations.RemoveField(
            model_name='subjectlocator',
            name='alt_contact_tel',
        ),
        migrations.RemoveField(
            model_name='subjectlocator',
            name='has_alt_contact',
        ),
        migrations.RemoveField(
            model_name='subjectlocator',
            name='other_alt_contact_cell',
        ),
        migrations.RemoveField(
            model_name='subjectlocator',
            name='site',
        ),
        migrations.AlterField(
            model_name='adverseevent',
            name='onset_date',
            field=models.DateField(default=datetime.datetime(2025, 3, 21, 9, 12, 31, 316278, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cbcbloodtestresult',
            name='date_tested',
            field=models.DateField(default=datetime.datetime(2025, 3, 21, 9, 12, 31, 315054, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='historicalsubjectscreening',
            name='report_datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 21, 9, 12, 31, 298224, tzinfo=utc), verbose_name='Report date and time.'),
        ),
        migrations.AlterField(
            model_name='subjectbloodsample',
            name='collection_date',
            field=models.DateField(default=datetime.datetime(2025, 3, 21, 9, 12, 31, 312623, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='subjectscreening',
            name='report_datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 21, 9, 12, 31, 298224, tzinfo=utc), verbose_name='Report date and time.'),
        ),
    ]
