# Generated by Django 2.2.1 on 2025-03-21 10:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mock_study_subjects', '0014_auto_20250321_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adverseevent',
            name='onset_date',
            field=models.DateField(default=datetime.datetime(2025, 3, 21, 10, 17, 57, 300706, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cbcbloodtestresult',
            name='date_tested',
            field=models.DateField(default=datetime.datetime(2025, 3, 21, 10, 17, 57, 299982, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='historicalsubjectscreening',
            name='report_datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 21, 10, 17, 57, 289557, tzinfo=utc), verbose_name='Report date and time.'),
        ),
        migrations.AlterField(
            model_name='subjectbloodsample',
            name='collection_date',
            field=models.DateField(default=datetime.datetime(2025, 3, 21, 10, 17, 57, 298587, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='subjectscreening',
            name='report_datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 21, 10, 17, 57, 289557, tzinfo=utc), verbose_name='Report date and time.'),
        ),
        migrations.AlterField(
            model_name='subjectvitals',
            name='diastolic_blood_pressure',
            field=models.IntegerField(default=0, help_text='mmHg'),
        ),
        migrations.AlterField(
            model_name='subjectvitals',
            name='heart_rate',
            field=models.IntegerField(default=0, help_text='bpm'),
        ),
        migrations.AlterField(
            model_name='subjectvitals',
            name='height',
            field=models.DecimalField(decimal_places=1, default=0, help_text='cm', max_digits=4),
        ),
        migrations.AlterField(
            model_name='subjectvitals',
            name='systolic_blood_pressure',
            field=models.IntegerField(default=0, help_text='mmHg'),
        ),
        migrations.AlterField(
            model_name='subjectvitals',
            name='weight',
            field=models.DecimalField(decimal_places=1, default=0, help_text='kg', max_digits=4),
        ),
    ]
