# Generated by Django 2.2.1 on 2025-05-09 08:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mock_study_subjects', '0018_auto_20250509_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adverseevent',
            name='onset_date',
            field=models.DateField(default=datetime.datetime(2025, 5, 9, 8, 37, 55, 64748, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cbcbloodtestresult',
            name='date_tested',
            field=models.DateField(default=datetime.datetime(2025, 5, 9, 8, 37, 55, 64201, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='historicalsubjectscreening',
            name='is_breastfeeding',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'Not applicable')], default='', help_text="If 'Yes', then stop. The patient cannot be part of this study.", max_length=20, verbose_name='Is the patient currently breastfeeding?'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalsubjectscreening',
            name='is_pregnant',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'Not applicable')], default='', help_text="If 'Yes', then stop. The patient cannot be part of this study. ", max_length=20, verbose_name='Are they currently pregnant?'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalsubjectscreening',
            name='report_datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 9, 8, 37, 55, 56549, tzinfo=utc), verbose_name='Report date and time.'),
        ),
        migrations.AlterField(
            model_name='subjectbloodsample',
            name='collection_date',
            field=models.DateField(default=datetime.datetime(2025, 5, 9, 8, 37, 55, 63240, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='subjectscreening',
            name='is_breastfeeding',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'Not applicable')], default='', help_text="If 'Yes', then stop. The patient cannot be part of this study.", max_length=20, verbose_name='Is the patient currently breastfeeding?'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subjectscreening',
            name='is_pregnant',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'Not applicable')], default='', help_text="If 'Yes', then stop. The patient cannot be part of this study. ", max_length=20, verbose_name='Are they currently pregnant?'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subjectscreening',
            name='report_datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 9, 8, 37, 55, 56549, tzinfo=utc), verbose_name='Report date and time.'),
        ),
    ]
