# Generated by Django 2.2.1 on 2025-05-13 14:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mock_study_subjects', '0021_auto_20250513_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseriskassessmentdemographics',
            name='occupation',
        ),
        migrations.AddField(
            model_name='baseriskassessmentdemographics',
            name='education_other',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="If you selected 'Other', please enter your level of education."),
        ),
        migrations.AddField(
            model_name='baseriskassessmentdemographics',
            name='employed',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='', max_length=3, verbose_name='Are you currently employed?'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adverseevent',
            name='onset_date',
            field=models.DateField(default=datetime.datetime(2025, 5, 13, 14, 21, 3, 598727, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='baseriskassessmentdemographics',
            name='marital_status_other',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name="If you selected 'Other', please enter your marital status."),
        ),
        migrations.AlterField(
            model_name='baseriskassessmentdemographics',
            name='race_other',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cbcbloodtestresult',
            name='date_tested',
            field=models.DateField(default=datetime.datetime(2025, 5, 13, 14, 21, 3, 598192, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='historicalsubjectscreening',
            name='report_datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 13, 14, 21, 3, 589820, tzinfo=utc), verbose_name='Report date and time.'),
        ),
        migrations.AlterField(
            model_name='subjectbloodsample',
            name='collection_date',
            field=models.DateField(default=datetime.datetime(2025, 5, 13, 14, 21, 3, 597067, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='subjectscreening',
            name='report_datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 13, 14, 21, 3, 589820, tzinfo=utc), verbose_name='Report date and time.'),
        ),
    ]
