# Generated by Django 2.2.1 on 2025-05-13 14:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mock_study_subjects', '0022_auto_20250513_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adverseevent',
            name='onset_date',
            field=models.DateField(default=datetime.datetime(2025, 5, 13, 14, 24, 34, 130471, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='baseriskassessmenthealth',
            name='heart_attack',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, verbose_name='Have you ever had a heart attack?'),
        ),
        migrations.AlterField(
            model_name='cbcbloodtestresult',
            name='date_tested',
            field=models.DateField(default=datetime.datetime(2025, 5, 13, 14, 24, 34, 129975, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='historicalsubjectscreening',
            name='report_datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 13, 14, 24, 34, 121966, tzinfo=utc), verbose_name='Report date and time.'),
        ),
        migrations.AlterField(
            model_name='subjectbloodsample',
            name='collection_date',
            field=models.DateField(default=datetime.datetime(2025, 5, 13, 14, 24, 34, 128918, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='subjectscreening',
            name='report_datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 13, 14, 24, 34, 121966, tzinfo=utc), verbose_name='Report date and time.'),
        ),
    ]
