# Generated by Django 2.2.1 on 2025-05-14 09:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import edc_base.model_fields.custom_fields


class Migration(migrations.Migration):

    dependencies = [
        ('mock_study_subjects', '0023_auto_20250513_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adverseevent',
            name='onset_date',
            field=models.DateField(default=datetime.datetime(2025, 5, 14, 9, 31, 16, 556893, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='baseriskassessmentdemographics',
            name='marital_status_other',
            field=edc_base.model_fields.custom_fields.OtherCharField(blank=True, max_length=20, null=True, verbose_name="If you selected 'Other', please enter your marital status."),
        ),
        migrations.AlterField(
            model_name='baseriskassessmentdemographics',
            name='race_other',
            field=edc_base.model_fields.custom_fields.OtherCharField(blank=True, max_length=10, null=True, verbose_name="If you selected 'Other, please enter your race.'"),
        ),
        migrations.AlterField(
            model_name='cbcbloodtestresult',
            name='date_tested',
            field=models.DateField(default=datetime.datetime(2025, 5, 14, 9, 31, 16, 556386, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='historicalsubjectscreening',
            name='report_datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 14, 9, 31, 16, 548285, tzinfo=utc), verbose_name='Report date and time.'),
        ),
        migrations.AlterField(
            model_name='subjectbloodsample',
            name='collection_date',
            field=models.DateField(default=datetime.datetime(2025, 5, 14, 9, 31, 16, 555327, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='subjectscreening',
            name='report_datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 14, 9, 31, 16, 548285, tzinfo=utc), verbose_name='Report date and time.'),
        ),
    ]
