# Generated by Django 2.2.1 on 2025-05-15 13:50

import _socket
import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django_revision.revision_field
import edc_base.model_fields.hostname_modification_field
import edc_base.model_fields.userfield
import edc_base.model_fields.uuid_auto_field
import edc_base.model_validators.date
import edc_base.utils
import edc_protocol.validators


class Migration(migrations.Migration):

    dependencies = [
        ('mock_study_subjects', '0025_auto_20250514_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseriskassessmentalcohol',
            name='consumes_alcohol',
        ),
        migrations.RemoveField(
            model_name='baseriskassessmentcaffeine',
            name='consumes_caffeine',
        ),
        migrations.AlterField(
            model_name='adverseevent',
            name='onset_date',
            field=models.DateField(default=datetime.datetime(2025, 5, 15, 13, 49, 44, 656691, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='baseriskassessmentalcohol',
            name='amount_of_drinks',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='When you do drink, how many drinks do you normally have?'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='baseriskassessmentalcohol',
            name='drinks_per_week',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)], verbose_name='How many days per week do you consume alcohol?'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='baseriskassessmentcaffeine',
            name='amount_of_drinks',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='How many drinks do you have on the days you do have cafinated drinks'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='baseriskassessmentcaffeine',
            name='drinks_per_week',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)], verbose_name='How many days per week do you have a cafinated drink?'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='baseriskassessmenthealth',
            name='side_effects',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True, verbose_name='Does the medication have increased blood pressure as a side effect?'),
        ),
        migrations.AlterField(
            model_name='cbcbloodtestresult',
            name='date_tested',
            field=models.DateField(default=datetime.datetime(2025, 5, 15, 13, 49, 44, 656100, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='drugresponse',
            name='response_datetime',
            field=models.DateTimeField(validators=[edc_base.model_validators.date.datetime_not_future, edc_protocol.validators.datetime_not_before_study_start], verbose_name='Date of the response assessment.'),
        ),
        migrations.AlterField(
            model_name='historicalsubjectscreening',
            name='report_datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 15, 13, 49, 44, 644755, tzinfo=utc), verbose_name='Report date and time.'),
        ),
        migrations.AlterField(
            model_name='subjectbloodsample',
            name='collection_date',
            field=models.DateField(default=datetime.datetime(2025, 5, 15, 13, 49, 44, 654146, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='subjectscreening',
            name='report_datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 15, 13, 49, 44, 644755, tzinfo=utc), verbose_name='Report date and time.'),
        ),
        migrations.CreateModel(
            name='BaseRiskAssessment',
            fields=[
                ('created', models.DateTimeField(blank=True, default=edc_base.utils.get_utcnow)),
                ('modified', models.DateTimeField(blank=True, default=edc_base.utils.get_utcnow)),
                ('user_created', edc_base.model_fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user created')),
                ('user_modified', edc_base.model_fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user modified')),
                ('hostname_created', models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60)),
                ('hostname_modified', edc_base.model_fields.hostname_modification_field.HostnameModificationField(blank=True, help_text='System field. (modified on every save)', max_length=50)),
                ('revision', django_revision.revision_field.RevisionField(blank=True, editable=False, help_text='System field. Git repository tag:branch:commit.', max_length=75, null=True, verbose_name='Revision')),
                ('device_created', models.CharField(blank=True, max_length=10)),
                ('device_modified', models.CharField(blank=True, max_length=10)),
                ('id', edc_base.model_fields.uuid_auto_field.UUIDAutoField(blank=True, editable=False, help_text='System auto field. UUID primary key.', primary_key=True, serialize=False)),
                ('consent_model', models.CharField(editable=False, max_length=50, null=True)),
                ('consent_version', models.CharField(editable=False, max_length=10, null=True)),
                ('report_datetime', models.DateTimeField(default=edc_base.utils.get_utcnow, help_text="If reporting today, use today's date/time, otherwise use the date/time this information was reported.", validators=[edc_protocol.validators.datetime_not_before_study_start, edc_base.model_validators.date.datetime_not_future], verbose_name='Report Date')),
                ('drinks_alcohol', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, verbose_name='Do you drink alcohol?')),
                ('drinks_caffeine', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, verbose_name='Do you drink caffinated drinks?')),
                ('subject_visit', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='mock_study_subjects.SubjectVisit')),
            ],
            options={
                'verbose_name': 'Base Risk Assessment',
                'verbose_name_plural': 'Base Risk Assessment',
                'abstract': False,
            },
        ),
    ]
