# Generated by Django 2.2.1 on 2025-03-12 14:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mock_study_subjects', '0032_auto_20250312_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalQuestionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_identifier', models.CharField(max_length=20)),
                ('participant_experience_with_the_study', models.TextField()),
                ('percieved_benefits', models.TextField()),
                ('percieved_challenges', models.TextField()),
                ('willingness_to_participate_in_future_studies', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Final Questionnaire',
                'verbose_name_plural': 'Final Questionnaire',
            },
        ),
        migrations.AlterField(
            model_name='subjectbloodsample',
            name='collection_date',
            field=models.DateField(default=datetime.datetime(2025, 3, 12, 14, 19, 39, 729329, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='subjectscreening',
            name='report_datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 12, 14, 19, 39, 717672, tzinfo=utc), verbose_name='Report date and time.'),
        ),
    ]
