# Generated by Django 2.2.1 on 2025-03-13 13:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mock_study_subjects', '0038_auto_20250313_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsubjectscreening',
            name='subject_identifier',
            field=models.CharField(db_index=True, default='', max_length=50, verbose_name='Subject Identifier'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjectscreening',
            name='subject_identifier',
            field=models.CharField(default='', max_length=50, unique=True, verbose_name='Subject Identifier'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adverseevent',
            name='onset_date',
            field=models.DateField(default=datetime.datetime(2025, 3, 13, 13, 18, 54, 780718, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cbcbloodtestresult',
            name='date_tested',
            field=models.DateField(default=datetime.datetime(2025, 3, 13, 13, 18, 54, 780066, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='historicalsubjectscreening',
            name='report_datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 13, 13, 18, 54, 774241, tzinfo=utc), verbose_name='Report date and time.'),
        ),
        migrations.AlterField(
            model_name='subjectbloodsample',
            name='collection_date',
            field=models.DateField(default=datetime.datetime(2025, 3, 13, 13, 18, 54, 778744, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='subjectscreening',
            name='report_datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 13, 13, 18, 54, 774241, tzinfo=utc), verbose_name='Report date and time.'),
        ),
    ]
