# Generated by Django 2.2.1 on 2025-03-14 13:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mock_study_subjects', '0044_auto_20250314_0640'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalsubjectscreening',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Mock Study Screening', 'verbose_name_plural': 'historical Mock Study Screening'},
        ),
        migrations.AlterModelOptions(
            name='subjectscreening',
            options={'verbose_name': 'Mock Study Screening', 'verbose_name_plural': 'Mock Study Screening'},
        ),
        migrations.AlterField(
            model_name='adverseevent',
            name='onset_date',
            field=models.DateField(default=datetime.datetime(2025, 3, 14, 13, 22, 40, 359661, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cbcbloodtestresult',
            name='date_tested',
            field=models.DateField(default=datetime.datetime(2025, 3, 14, 13, 22, 40, 358570, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='historicalsubjectscreening',
            name='report_datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 14, 13, 22, 40, 350612, tzinfo=utc), verbose_name='Report date and time.'),
        ),
        migrations.AlterField(
            model_name='subjectbloodsample',
            name='anticoagulant',
            field=models.CharField(choices=[('heparin', 'Heparin'), ('citrate', 'Citrate')], max_length=50),
        ),
        migrations.AlterField(
            model_name='subjectbloodsample',
            name='collection_date',
            field=models.DateField(default=datetime.datetime(2025, 3, 14, 13, 22, 40, 356328, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='subjectbloodsample',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete')], max_length=20),
        ),
        migrations.AlterField(
            model_name='subjectbloodsample',
            name='storage_location',
            field=models.CharField(choices=[('optimum_health_medical_laboratory', 'Optimum Health Mediacal Laboratory'), ('diagnofirm_medical_laboratories', 'Diagnofirm Medical Laboratories'), ('mmoloki_medical_laboratories', 'Mmoloki Medical Laboratories')], max_length=50),
        ),
        migrations.AlterField(
            model_name='subjectscreening',
            name='report_datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 14, 13, 22, 40, 350612, tzinfo=utc), verbose_name='Report date and time.'),
        ),
    ]
