# Generated by Django 2.2.1 on 2025-03-06 09:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mock_study_subjects', '0012_auto_20250306_0907'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment', models.CharField(max_length=10)),
                ('reason', models.CharField(choices=[('Quarterly visit/contact', 'Quarterly visit/contact'), ('Unscheduled visit/contact', 'Unscheduled visit/contact'), ('Missed quarterly visit', 'Missed quarterly visit'), ('Lost to follow-up', 'Lost to follow-up (use only when taking subject off study)'), ('Death', 'Death'), ('off study', 'Off study'), ('deferred', 'Deferred')], max_length=25, verbose_name='What is the reason for this visit report?')),
                ('reason_unscheduled', models.CharField(choices=[('Routine oncology', 'Routine oncology clinic visit (i.e. planned chemo, follow-up)'), ('Ill oncology', 'Ill oncology clinic visit'), ('Patient called', 'Patient called to come for visit'), ('N/A', 'Not Applicable'), ('OTHER', 'Other, specify:')], default='N/A', max_length=50, verbose_name="If 'Unscheduled' above, provide reason for the unscheduled visit")),
                ('info_source', models.CharField(choices=[('Clinic visit w/ subject', 'Clinic visit with participant'), ('Other contact w/ subject', 'Other contact with participant (i.e telephone call)'), ('Contact w/ health worker', 'Contact with health care worker'), ('Contact w/ family/design', 'Contact with family or designated person who can provide information'), ('OTHER', 'Other,specify')], max_length=40, verbose_name='What is the main source of this information?')),
            ],
        ),
        migrations.AlterField(
            model_name='subjectscreening',
            name='report_datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 6, 9, 9, 46, 925526, tzinfo=utc), verbose_name='Report date and time.'),
        ),
    ]
