# Generated by Django 2.2.1 on 2025-03-10 10:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mock_study_subjects', '0020_auto_20250310_0904'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectVitals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_identifier', models.CharField(max_length=10)),
                ('collection_site', models.CharField(choices=[('gaborone_private_hospital', 'Gaborone Private Hospital (GPH)'), ('nyangabgwe_referral_Hospital', 'Nyangabgwe Referral Hospital (NRH)'), ('princess_marina_hospital', 'Princess Marina Hospital (PMH)'), ('bokamoso_private_hospital', 'Bokamoso Private Hospital (BPH)')], max_length=50)),
                ('were_vitals_collected', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('measurement_date', models.DateField()),
                ('systolic_blood_pressure', models.IntegerField()),
                ('diastolic_blood_pressure', models.IntegerField()),
                ('anatomical_location_of_measurement', models.CharField(max_length=50)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('is_baseline', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Subject Vitals',
                'verbose_name_plural': 'Subject Vitals',
            },
        ),
        migrations.AlterField(
            model_name='subjectscreening',
            name='report_datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 10, 10, 33, 19, 50890, tzinfo=utc), verbose_name='Report date and time.'),
        ),
    ]
