# Generated by Django 2.2.1 on 2025-03-11 12:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mock_study_subjects', '0021_auto_20250310_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectscreening',
            name='report_datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 11, 12, 57, 36, 456493, tzinfo=utc), verbose_name='Report date and time.'),
        ),
        migrations.AlterField(
            model_name='subjectvitals',
            name='is_baseline',
            field=models.BooleanField(verbose_name="Is this the participant's baseline vitals measurement?"),
        ),
    ]
