# Generated by Django 2.2.1 on 2025-03-11 14:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mock_study_subjects', '0023_auto_20250311_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectbloodsample',
            name='collection_date',
            field=models.DateField(default=datetime.datetime(2025, 3, 11, 14, 3, 43, 655111, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='subjectscreening',
            name='report_datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 11, 14, 3, 43, 642573, tzinfo=utc), verbose_name='Report date and time.'),
        ),
    ]
