# Generated by Django 2.2.1 on 2025-03-13 07:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mock_study_subjects', '0034_auto_20250312_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='cbcbloodtestresult',
            name='date_tested',
            field=models.DateField(default=datetime.datetime(2025, 3, 13, 7, 12, 7, 40221, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='cbcbloodtestresult',
            name='test_site',
            field=models.CharField(choices=[('optimum_health_medical_laboratory', 'Optimum Health Mediacal Laboratory'), ('diagnofirm_medical_laboratories', 'Diagnofirm Medical Laboratories'), ('mmoloki_medical_laboratories', 'Mmoloki Medical Laboratories')], default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cbcbloodtestresult',
            name='testing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete')], default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adverseevent',
            name='onset_date',
            field=models.DateField(default=datetime.datetime(2025, 3, 13, 7, 12, 7, 41369, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='subjectbloodsample',
            name='collection_date',
            field=models.DateField(default=datetime.datetime(2025, 3, 13, 7, 12, 7, 38050, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='subjectscreening',
            name='report_datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 13, 7, 12, 7, 26655, tzinfo=utc), verbose_name='Report date and time.'),
        ),
    ]
